### ISSUE TITLE
Stats for Flagstone changed to be beautiful

### ISSUE THREAD

**Issue by Amnesiac9** [FluffierThanThou/StuffedFloors#11]
The original stats for Flagstone should be 0 beauty, but in StoneFloors.xml they are set to ParentName="StuffedFloorsStonePrettyBase"> instead of BasicBase

Edit: I wanted to note that this is a minor issue that I hope you can fix in the next release but nothing that needs rushing of course, I just wanted to let you know :^)

**Comment by FluffierThanThou** [comment]
what can I say, I like flagstones :P
