### ISSUE TITLE
cleanliness bonus on  metal floors?

### ISSUE THREAD

**Issue by FluffierThanThou** [FluffierThanThou/StuffedFloors#20]
Fluffy  [author] Just now 
@apexii; do all metal floors give a bonus in vanilla? I thought it was only the silver tiles?

Anyway, no, I don't think they currently give that bonus, but I'll have a look to make sure they match vanilla in that regard.

apexii 4 Sep @ 5:01am 
Do the metal floors (plates) give a bonus to cleanliness like the vanilla metal floors or is it really just "a generic metal flooring"? Cause I'd love to have that bonus back.

**Comment by InsanityPrelude** [comment]
Fixed by #27 which adds a cleanliness of 0.2 to all metal tiles in keeping with vanilla. 

Now has a nice gradient.

Floors = 0
Metal Tiles = 0.2
Metal Grate = 0.4  (but it's ugly...)
Sterile Tile = 0.6   (but it's expensive...)
