### ISSUE TITLE
adds wealth for natural tiles to colony wealth?

### ISSUE THREAD

**Issue by FluffierThanThou** [FluffierThanThou/StuffedFloors#32]
**reported by:**  
nemuineru

**description:**  
> I activated this mod, and seems it is bugged. Stuffed Floor causes miscounts the Natural tile price of all Map Cells(like Dirt , mud, rough rock tile) to my Building Wealth, again. (2018/09/22)Which leads Skyrockets players wealth, I suggest you to investigate this problem.

**Comment by Azzzil** [comment]
Hello, I have also had this issue and I was able to replicate it both without my modpack and with it  I was having an issue making a full video so I uploaded it in 2 parts on streamable. 
https://streamable.com/w67hnm - With Stuffed Floors 
https://streamable.com/utux0g - Without Stuffed Floors

**Comment by LucasOCastro** [comment]
Removing most of the [T] More Floors entries from StoneFloors.xml removed this issue for me. From line 131 to line 266. Removing individual entries did not fix it, so far it seems that it is necessary to remove everything between those two lines. No idea of what could possibly cause this, but those defs simply existing is enough to glitch the wealth

**Comment by LucasOCastro** [comment]
Update: Removing from 161 to 266 seems to be enough. This is not a problem about counting natural tiles, removing the every single one of the following defs fixed it:

- StuffedStoneStaggered
- StuffedStoneAlternating
- StuffedStoneHerringbone
- StuffedStoneDigital
- StuffedStoneDiamond
- StuffedStoneTiles
- StuffedStoneMosaic

Of course, removing them isnt a fix per se, but it makes the mod usable and may help figuring out what's going wrong with those defs specifically.
