### ISSUE TITLE
A17 Object Reference not set to an instance of an object error in console when attempting to place stone variants of stuffed floors

### ISSUE THREAD

**Issue by SirJimmyRocket** [FluffierThanThou/StuffedFloors#5]
Able to replicate with ONLY Artictect Sense and Stuffed Floors installed, and in the proper load order.
Though with this stack trace... I was kinda lazy and left all of the mods im trying to use in.

Modlist in order:
Core, HugsLib, ArchitectSense, LT-DoorMat, Quarry, Editable Backstories, Basic Bridges, Smooth Stone Walls, StackMerger, StuffedFloors, Wild Cultivation, and Vegetable Garden 5.4 

Behaviour in game without devmode enabled is... when selecting the stone slab floor it doesn't allow the selection of a material. The object texture in the arcitecture menu turns grey, and the game cursor generally shows the material being "used" is either 30 silver, or 3 wood.

Clicking and dragging a section of flooring doesn't do anything, aside from generate the error below.

RimWorld 0.17.1535 rev1116
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
RimWorld.VersionControl:LogVersionNumber() (at C:\Dev\RimWorld\Assets\Scripts\RimWorld\Utility\Version\VersionControl.cs:83)
Verse.Root:CheckGlobalInit() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root.cs:76)
Verse.Root:Start() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root.cs:31)
Verse.Root_Entry:Start() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:16)

ArchitectSense :: Creating subcategories
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
ArchitectSense.Logger:Message(String, Object[])
ArchitectSense.Controller:Initialize()
ArchitectSense.Init:.cctor()
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(IntPtr)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(RuntimeTypeHandle) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs:101)
Verse.StaticConstructorOnStartupUtility:CallAll() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\StaticConstructorOnStartup.cs:26)
Verse.PlayDataLoader:<DoPlayLoad>m__80C() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Defs\Databases\PlayDataLoader.cs:256)
Verse.LongEventHandler:ExecuteToExecuteWhenFinished() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:473)
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:388)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:243)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

Vanilla Backstory Database Cleared.
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

Backstories in REB Backstory Database:
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

   Childhood backstories (shuffleable): 124
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

   Childhood backstories (non-shuffleable): 0
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

   Adulthood backstories (shuffleable): 156
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

   Adulthood backstories (non-shuffleable): 0
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

HAF Backstories Added to REB Database:
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

   HAF Childhood backstories (shuffleable): 0
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

   HAF Childhood backstories (non-shuffleable): 0
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

   HAF Adulthood backstories (shuffleable): 0
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

   HAF Adulthood backstories (non-shuffleable): 0
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

Vanilla Name Database *NOT* Cleared.
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

Names Added to Vanilla Name Database:
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

   First Names: 0
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

   Nicknames: 0
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

   Last Names: 0
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

   Full Names (without bios): 7
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

   Full Names (with bios): 10
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
REB_Code.REB_Initializer:Setup()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:405)
Verse.LongEventHandler:LongEventsUpdate(Boolean&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:245)
Verse.Root:Update_Patch1(Object)
Verse.Root_Entry:Update() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Entry.cs:25)

Loaded file (Scenario) is from version 0.17.1530 rev959, we are running version 0.17.1535 rev1116.
Verse.Log:Warning(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:36)
Verse.ScribeMetaHeaderUtility:LoadGameDataHeader(ScribeHeaderMode, Boolean) (at C:\Dev\RimWorld\Assets\Scripts\Verse\SaveLoad\Scribe\ScribeMetaHeaderUtility.cs:86)
Verse.GameDataSaveLoader:TryLoadScenario(String, ScenarioCategory, Scenario&) (at C:\Dev\RimWorld\Assets\Scripts\Verse\SaveLoad\GameDataSaveLoader.cs:73)
RimWorld.ScenarioFiles:RecacheData() (at C:\Dev\RimWorld\Assets\Scripts\RimWorld\Scenario\ScenarioLister\ScenarioFiles.cs:44)
RimWorld.ScenarioLister:RecacheData() (at C:\Dev\RimWorld\Assets\Scripts\RimWorld\Scenario\ScenarioLister\ScenarioLister.cs:93)
RimWorld.ScenarioLister:RecacheIfDirty() (at C:\Dev\RimWorld\Assets\Scripts\RimWorld\Scenario\ScenarioLister\ScenarioLister.cs:84)
RimWorld.<ScenariosInCategory>c__Iterator127:MoveNext() (at C:\Dev\RimWorld\Assets\Scripts\RimWorld\Scenario\ScenarioLister\ScenarioLister.cs:36)
System.Linq.Enumerable:FirstOrDefault(IEnumerable`1)
RimWorld.Page_SelectScenario:EnsureValidSelection() (at C:\Dev\RimWorld\Assets\Scripts\RimWorld\UI\Entry\Page_SelectScenario.cs:273)
RimWorld.Page_SelectScenario:PreOpen() (at C:\Dev\RimWorld\Assets\Scripts\RimWorld\UI\Entry\Page_SelectScenario.cs:38)
Verse.WindowStack:Add(Window) (at C:\Dev\RimWorld\Assets\Scripts\Verse\UI\Windows\WindowStack.cs:319)
RimWorld.MainMenuDrawer:<DoMainMenuControls>m__5FE() (at C:\Dev\RimWorld\Assets\Scripts\RimWorld\UI\Entry\MainMenuDrawer.cs:125)
Verse.ListableOption:DrawOption(Vector2, Single) (at C:\Dev\RimWorld\Assets\Scripts\Verse\UI\Utility\OptionListingUtility.cs:35)
Verse.OptionListingUtility:DrawOptionListing(Rect, List`1) (at C:\Dev\RimWorld\Assets\Scripts\Verse\UI\Utility\OptionListingUtility.cs:127)
RimWorld.MainMenuDrawer:DoMainMenuControls(Rect, Boolean) (at C:\Dev\RimWorld\Assets\Scripts\RimWorld\UI\Entry\MainMenuDrawer.cs:218)
RimWorld.MainMenuDrawer:MainMenuOnGUI() (at C:\Dev\RimWorld\Assets\Scripts\RimWorld\UI\Entry\MainMenuDrawer.cs:98)
Verse.UIRoot_Entry:DoMainMenu() (at C:\Dev\RimWorld\Assets\Scripts\Verse\UI\Entry\UIRoot_Entry.cs:108)
Verse.UIRoot_Entry:UIRootOnGUI() (at C:\Dev\RimWorld\Assets\Scripts\Verse\UI\Entry\UIRoot_Entry.cs:61)
Verse.Root:OnGUI() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root.cs:151)

Initializing new game with mods Core, HugsLib, ArchitectSense, LT-DoorMat, QRY, 922168141, 920546527, 921056372, StackMerger, StuffedFloors, 922158160, and Vegetable Garden 5.4
Verse.Log:Message(String) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Debug\Log\Log.cs:30)
Verse.Game:InitNewGame() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Game\Game.cs:269)
Verse.Root_Play:<Start>m__84D() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root_Play.cs:43)
Verse.LongEventHandler:RunEventFromAnotherThread(Action) (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:439)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__849() (at C:\Dev\RimWorld\Assets\Scripts\Verse\Global\LongEventHandler.cs:353)

Object reference not set to an instance of an object
  at Verse.GenSpawn.WipeExistingThings (IntVec3 thingPos, Rot4 thingRot, Verse.BuildableDef thingDef, Verse.Map map, DestroyMode mode) [0x00000] in C:\Dev\RimWorld\Assets\Scripts\Verse\Utility\Gen\Placement\GenSpawn.cs:82 
  at RimWorld.Designator_Build.DesignateSingleCell (IntVec3 c) [0x000b8] in C:\Dev\RimWorld\Assets\Scripts\RimWorld\UI\Designators\Place\Designator_Build.cs:280 
  at Verse.Designator.DesignateMultiCell (IEnumerable`1 cells) [0x0004d] in C:\Dev\RimWorld\Assets\Scripts\Verse\UI\Designator\Designator.cs:113 
  at Verse.DesignatorManager.ProcessInputEvents () [0x0014c] in C:\Dev\RimWorld\Assets\Scripts\Verse\UI\Designator\DesignatorManager.cs:105 
  at RimWorld.MapInterface.HandleMapClicks () [0x00021] in C:\Dev\RimWorld\Assets\Scripts\RimWorld\UI\MapInterface.cs:142 
  at RimWorld.UIRoot_Play.UIRootOnGUI () [0x00143] in C:\Dev\RimWorld\Assets\Scripts\RimWorld\UI\UIRoot_Play.cs:96 
  at Verse.Root.OnGUI () [0x00046] in C:\Dev\RimWorld\Assets\Scripts\Verse\Global\Root\Root.cs:151

**Comment by FluffierThanThou** [comment]
hmm, odd that there's such a difference between devmode on and off. Thanks for reporting, looking into it now.

**Comment by FluffierThanThou** [comment]
ahh, no, there's is no real difference, construction in dev mode just skips the blueprint step, hiding the symptoms

**Comment by FluffierThanThou** [comment]
I managed to not actually add the generated terrain defs to the database, which in turn meant there were no blueprints or frames generated. Silly mistake, took me a while to diagnose though. 

It should work now, make sure to also update ArchitectSense.

**Comment by SirJimmyRocket** [comment]
That was quick! Downloaded and can confirm issue looks to be resolved.
