### ISSUE TITLE
subcategories broken for More Floors

### ISSUE THREAD

**Issue by cucumpear** [FluffierThanThou/StuffedFloors#8]
Since the newest update I'm seeing the More Floors carpets and chequered tiles as both subcategory and individual items. I tested it with minimal mods to check for incompatibilities (using all steam versions except for Stuffed Floors, which I redownloaded after the issue appeared), but the behaviour persists. I don't think it's Architect Sense itself, since other mods which use subcategories are fine.

**Comment by FluffierThanThou** [comment]
Are you sure this still persists after the fix to Stuffed Floors? I haven't had any further reports on steam since...

**Comment by cucumpear** [comment]
That's why I was confused, someone else would surely have also reported this. I'll try again using fresh local files.

**Comment by cucumpear** [comment]
Still happening with all three redownloaded and reinstalled. I first tested in "easy mode" with HugsLib and Mod List Backup, then just to be sure I deleted the entire Ludeon folder in AppData and just ran Architect Sense, More Floors and Stuffed Floors (in that order, I've also had MF and SF switched with the same result), still getting the extra carpets and chequerboards.
If you can't replicate that I'll just assume it's a weird local derp, but since I can't get rid of the issue and I'm not completely clueless with RW mods I figured I should report it.

**Comment by FluffierThanThou** [comment]
It's entirely possible I may have missed something, although this does seem like something even my usual quick check should have found. I'll have a better look tonight, any chance you could provide me with an output log? There might be some clues hiding in there.

To be honest, it's not possible for me to thoroughly test everything and still keep all my mods up to date (and occasionally come up with something new). I have to rely on people like you to put in bug reports when I invariably cock something up. In other words, you're an invaluable part of the development process, so keep those reports coming 👍.

**Comment by cucumpear** [comment]
The log doesn't look very helpful and I'll do some more in depth xml checking, since that's something I can do.
[output_log.txt](https://github.com/FluffierThanThou/StuffedFloors/files/1205650/output_log.txt)
